# Generated by Django 3.1.4 on 2021-03-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('imgurl', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=40)),
                ('registrationdate', models.DateField()),
                ('role', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'user_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usertable')),
                ('amount', models.IntegerField()),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.DO_NOTHING, to='app.products')),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
                'unique_together': {('userid', 'productid')},
            },
        ),
    ]
